# Uso de imagen
FROM apache/airflow:2.6.2

# Insatalación libreiras
RUN pip install pandas requests sqlalchemy psycopg2-binary



# copiar archivo dentro de contenedor
COPY dags/cuarta_entrega.py /opt/airflow/dags/

#Iniciar aiflow
RUN airflow db init 

CMD ["webserver"]
