# Imagen utilizada
FROM python:3.7

# Pasamos los archibos necesario al interior de la imagen
COPY dags/tercera_entrega.py /usr/local/airflow/dags/tercera_entrega.py

# Instala las dependencias de Airflow
RUN pip install apache-airflow==2.2.2 \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.2.2/constraints-3.7.txt"

# Configura las variables de entorno necesarias
ENV AIRFLOW_HOME=/usr/local/airflow
ENV PYTHONPATH="${PYTHONPATH}:/usr/local/airflow"

# Inicializa la base de datos de Airflow
RUN airflow db init

# Inicia el scheduler de Airflow en segundo plano
CMD ["airflow", "scheduler"]